//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AuthEvent struct {
	ID        int64 `sql:"primary_key"`
	UserID    *int64
	Action    string
	Detail    string
	CreatedAt time.Time
}
