// generated by unplugin-svelte-components
// We suggest you to commit this file into source control
declare global {
    const Button: typeof import("./components/Button.svelte")["default"]
    const FormItem: typeof import("./components/FormItem.svelte")["default"]
    const FormLogin: typeof import("./ui/FormLogin.svelte")["default"]
    const FormRegister: typeof import("./ui/FormRegister.svelte")["default"]
    const FormResetPassword: typeof import("./ui/FormResetPassword.svelte")["default"]
    const Input: typeof import("./components/Input.svelte")["default"]
    const Tabs: typeof import("./components/Tabs.svelte")["default"]
}

export {}
