//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type AuthUser struct {
	ID        int32 `sql:"primary_key"`
	Username  string
	Email     string
	Role      string
	Password  string
	CreatedAt time.Time
	LastLogin time.Time
	Attr      string
}
